language: c

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $TRAVIS_OS_NAME
  - uname -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq

install:
  - sudo apt-cache madison cmake
  - wget "http://www.cmake.org/files/v3.0/cmake-3.0.0.tar.gz"
  - openssl sha1 "cmake-3.0.0.tar.gz"
  - tar xf "cmake-3.0.0.tar.gz"
  - cd "cmake-3.0.0"
  - ./bootstrap --prefix=~
  - make
  - make install
  - export PATH="~/bin:${PATH}"
  - cd ..
  - which cmake
  - cmake --version

before_script:
  - mkdir buildx
  - cd buildx
  - which cmake
  - ~/bin/cmake ..

script:
  - pwd
  - which cmake
  - ~/bin/cmake --build . --config Release

branches:
  only:
    - master

os:
  - linux
  - osx

osx_image: xcode61
